// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsUserNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USER_NOT_FOUND.String() && e.Code == 500
}

func ErrorUserNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_USER_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsUserExists(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USER_EXISTS.String() && e.Code == 500
}

func ErrorUserExists(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_USER_EXISTS.String(), fmt.Sprintf(format, args...))
}

func IsUsernameHasChinese(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USERNAME_HAS_CHINESE.String() && e.Code == 500
}

func ErrorUsernameHasChinese(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_USERNAME_HAS_CHINESE.String(), fmt.Sprintf(format, args...))
}

func IsPasswordError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_PASSWORD_ERROR.String() && e.Code == 500
}

func ErrorPasswordError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_PASSWORD_ERROR.String(), fmt.Sprintf(format, args...))
}
