// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"demo/app/gateway/interface/internal/biz"
	"demo/app/gateway/interface/internal/conf"
	"demo/app/gateway/interface/internal/data"
	"demo/app/gateway/interface/internal/server"
	"demo/app/gateway/interface/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	gatewayRepo := data.NewGatewayRepo(dataData, logger)
	gatewayUsecase := biz.NewGatewayUsecase(gatewayRepo, logger)
	gatewayService := service.NewGatewayService(gatewayUsecase)
	httpServer := server.NewHTTPServer(confServer, gatewayService, logger)
	app := newApp(logger, confData, dataData, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
